//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Desease_Details
    {
        public int detail_id { get; set; }
        public Nullable<int> patient_id { get; set; }
        public Nullable<int> no_of_visits { get; set; }
        public string desease_catagory { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
