//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int paymentId { get; set; }
        public string patientId { get; set; }
        public Nullable<int> total_bill { get; set; }
        public Nullable<bool> isRequested { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
